import pandas as pd
from datetime import datetime

def generate_html(predictions, output_path="index.html", ticker_map=None):
    """
    予測結果を受け取り、HTMLレポートを出力する
    ticker_map: { code: name }
    """
    if predictions.empty:
        print("No predictions to report.")
        return

    # 予測日
    target_date = predictions['Date'].iloc[0].strftime('%Y-%m-%d')
    
    # 上位・下位の抽出
    top_picks = predictions.head(10)
    bottom_picks = predictions.tail(10)
    
    # HTML生成 (f-stringで簡易テンプレート)
    html_content = f"""
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Stock Prediction Report ({target_date})</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #f4f4f9; color: #333; margin: 0; padding: 20px; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 20px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); border-radius: 8px; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #f8f9fa; font-weight: bold; }}
        tr:hover {{ background-color: #f1f1f1; }}
        .rank-up {{ color: #e74c3c; font-weight: bold; }}
        .rank-down {{ color: #27ae60; font-weight: bold; }}
        .footer {{ margin-top: 40px; font-size: 0.8em; color: #7f8c8d; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>AI Stock Prediction Report</h1>
        <p><strong>Prediction Date:</strong> {target_date} (Based on data up to this date)</p>
        <p>This report ranks stocks based on their predicted relative return for the next 5 business days.</p>
        
        <h2>🚀 Top 10 Picks (Long Candidate)</h2>
        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Current Price</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                {_generate_table_rows(top_picks, ticker_map)}
            </tbody>
        </table>
        
        <h2>📉 Bottom 10 Picks (Short Candidate)</h2>
        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Current Price</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                {_generate_table_rows(bottom_picks, ticker_map)}
            </tbody>
        </table>
        
        <div class="footer">
            Generated by AI-Quant System | Run at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </div>
</body>
</html>
    """
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"HTML Report saved to {output_path}")

def _generate_table_rows(df, ticker_map=None):
    rows = ""
    for _, row in df.iterrows():
        score = row['Predicted_Return']
        code = row['SecuritiesCode']
        name = ticker_map.get(code + ".T", code) if ticker_map else code
        # Code typically comes as "XXXX" string from predictor. Map keys are "XXXX.T"
        # Try both formats just in case
        if ticker_map and code not in ticker_map and (code + ".T") in ticker_map:
             name = ticker_map[code + ".T"]
        
        rows += f"""
        <tr>
            <td>{int(row['Rank'])}</td>
            <td>{code}</td>
            <td>{name}</td>
            <td>{row['Close']:.1f}</td>
            <td>{score:.4f}</td>
        </tr>
        """
    return rows
